on:
  push:
    branches:
      - main
  schedule:
    - cron: "28 9 * * *"

jobs:
  apply:
    name: Apply rcmt packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          RCMT_GIT_EMAIL: hydrantanderwand@gmail.com
          RCMT_GIT_USERNAME: wndhydrnt
          RCMT_GITHUB_ACCESS_TOKEN: ${{ secrets.RCMT_GITHUB_ACCESS_TOKEN }}
          RCMT_GITHUB_USERNAME: ${{ secrets.RCMT_GITHUB_USERNAME }}
        run: make apply
